name = "QuasiCrystal"
uuid = "7178fac9-d2bf-4933-964d-a28131e4f2a4"
version = "0.1.0"
authors = ["sotashimozono <shimozono-sota631@g.ecc.u-tokyo.ac.jp>"]

[deps]
LinearAlgebra = "37e2e46d-f89d-539d-b4ee-838fcccc9c8e"
Plots = "91a5bcdd-55d7-5caf-9e0b-520d859cae80"
SparseArrays = "2f01184e-e22b-5df5-ae63-d93ebab69eaf"
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[compat]
LinearAlgebra = "1.12.0"
Plots = "1.41.2"
SparseArrays = "1.12.0"
Test = "1.11.0"
